// <auto-generated />
using System;
using CoreCRUD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreCRUD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("CoreCRUD.Models.Collectible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<DateTime>("DateOfPurchase");

                    b.Property<string>("ManufacturerID");

                    b.Property<int?>("ManufacturerID1");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerID1");

                    b.ToTable("Collectible");
                });

            modelBuilder.Entity("CoreCRUD.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Model");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("CoreCRUD.Models.Collectible", b =>
                {
                    b.HasOne("CoreCRUD.Models.Manufacturer", "Manufacturer")
                        .WithMany("Collectibles")
                        .HasForeignKey("ManufacturerID1");
                });
#pragma warning restore 612, 618
        }
    }
}
